services:
  db:
    image: postgres
    pull_policy: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test_db

    ports:
      - "5432:5432"
