services:
  backend:
    image: st333phanie/react-flask-note-app-backend:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: ${POSTGRES_HOST}

      AES_ENCRYPTION_KEY: ${AES_ENCRYPTION_KEY}
      AES_INITIALISATION_VECTOR: ${AES_INITIALISATION_VECTOR}
      
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      FLASK_APP_CLIENT_URL: ${FLASK_APP_CLIENT_URL}
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./backend:/usr/src/app
  
  frontend:
    image: st333phanie/react-flask-note-app-frontend:latest
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      
    ports:
      - "3000:3000"