services:
  backend:
    image: st333phanie/react-flask-note-app-backend:latest
    ports:
      - "8000:8000"
  
  frontend:
    image: st333phanie/react-flask-note-app-frontend:latest
    ports:
      - "3000:3000"